[2023-07-17T15:46:55.318+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.preprocessing.remove_plural manual__2023-07-17T15:36:11.586553+00:00 [queued]>
[2023-07-17T15:46:55.329+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.preprocessing.remove_plural manual__2023-07-17T15:36:11.586553+00:00 [queued]>
[2023-07-17T15:46:55.329+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-17T15:46:55.344+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): preprocessing.remove_plural> on 2023-07-17 15:36:11.586553+00:00
[2023-07-17T15:46:55.349+0000] {standard_task_runner.py:57} INFO - Started process 1233 to run task
[2023-07-17T15:46:55.352+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'preprocessing.remove_plural', 'manual__2023-07-17T15:36:11.586553+00:00', '--job-id', '712', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpz5xzfbja']
[2023-07-17T15:46:55.355+0000] {standard_task_runner.py:85} INFO - Job 712: Subtask preprocessing.remove_plural
[2023-07-17T15:46:55.399+0000] {task_command.py:410} INFO - Running <TaskInstance: main_dag.preprocessing.remove_plural manual__2023-07-17T15:36:11.586553+00:00 [running]> on host 78942c037002
[2023-07-17T15:46:55.494+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='preprocessing.remove_plural' AIRFLOW_CTX_EXECUTION_DATE='2023-07-17T15:36:11.586553+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-17T15:36:11.586553+00:00'
[2023-07-17T15:47:16.993+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main_dag.py", line 109, in remove_plural
    nx.write_graphml(graph, f"data/{kwargs['write_filename']}")
  File "/home/airflow/.local/lib/python3.7/site-packages/networkx/utils/decorators.py", line 795, in func
    return argmap._lazy_compile(__wrapper)(*args, **kwargs)
  File "<class 'networkx.utils.decorators.argmap'> compilation 14", line 5, in argmap_write_graphml_lxml_10
    import warnings
  File "/home/airflow/.local/lib/python3.7/site-packages/networkx/readwrite/graphml.py", line 178, in write_graphml_lxml
    edge_id_from_attribute=edge_id_from_attribute,
  File "/home/airflow/.local/lib/python3.7/site-packages/networkx/readwrite/graphml.py", line 729, in __init__
    self.add_graph_element(graph)
  File "/home/airflow/.local/lib/python3.7/site-packages/networkx/readwrite/graphml.py", line 770, in add_graph_element
    T = self.xml_type[self.attr_type(k, "node", v)]
KeyError: <class 'dict'>
[2023-07-17T15:47:17.002+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=main_dag, task_id=preprocessing.remove_plural, execution_date=20230717T153611, start_date=20230717T154655, end_date=20230717T154717
[2023-07-17T15:47:17.017+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 712 for task preprocessing.remove_plural (<class 'dict'>; 1233)
[2023-07-17T15:47:17.064+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-17T15:47:17.101+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
