[2023-07-16T16:14:45.641+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.install_libraries manual__2023-07-16T16:14:44.118515+00:00 [queued]>
[2023-07-16T16:14:45.650+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.install_libraries manual__2023-07-16T16:14:44.118515+00:00 [queued]>
[2023-07-16T16:14:45.651+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-16T16:14:45.665+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): install_libraries> on 2023-07-16 16:14:44.118515+00:00
[2023-07-16T16:14:45.669+0000] {standard_task_runner.py:57} INFO - Started process 2642 to run task
[2023-07-16T16:14:45.672+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'install_libraries', 'manual__2023-07-16T16:14:44.118515+00:00', '--job-id', '601', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpe_wuk5pf']
[2023-07-16T16:14:45.673+0000] {standard_task_runner.py:85} INFO - Job 601: Subtask install_libraries
[2023-07-16T16:14:45.718+0000] {task_command.py:410} INFO - Running <TaskInstance: main_dag.install_libraries manual__2023-07-16T16:14:44.118515+00:00 [running]> on host 1696d5f40b5e
[2023-07-16T16:14:45.830+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='install_libraries' AIRFLOW_CTX_EXECUTION_DATE='2023-07-16T16:14:44.118515+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-16T16:14:44.118515+00:00'
[2023-07-16T16:14:45.831+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-16T16:14:45.832+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'pip install networkx matplotlib scipy seaborn']
[2023-07-16T16:14:45.843+0000] {subprocess.py:86} INFO - Output:
[2023-07-16T16:14:46.500+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-07-16T16:14:46.654+0000] {subprocess.py:93} INFO - Requirement already satisfied: networkx in /home/***/.local/lib/python3.7/site-packages (2.6.3)
[2023-07-16T16:14:46.654+0000] {subprocess.py:93} INFO - Requirement already satisfied: matplotlib in /home/***/.local/lib/python3.7/site-packages (3.5.3)
[2023-07-16T16:14:46.655+0000] {subprocess.py:93} INFO - Requirement already satisfied: scipy in /home/***/.local/lib/python3.7/site-packages (1.7.3)
[2023-07-16T16:14:54.821+0000] {subprocess.py:93} INFO - WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f95d43bb710>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/seaborn/
[2023-07-16T16:14:58.019+0000] {subprocess.py:93} INFO - Collecting seaborn
[2023-07-16T16:14:58.495+0000] {subprocess.py:93} INFO -   Downloading seaborn-0.12.2-py3-none-any.whl (293 kB)
[2023-07-16T16:14:58.571+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 293.3/293.3 kB 4.0 MB/s eta 0:00:00
[2023-07-16T16:14:58.617+0000] {subprocess.py:93} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.7/site-packages (from matplotlib) (0.11.0)
[2023-07-16T16:14:58.618+0000] {subprocess.py:93} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.7/site-packages (from matplotlib) (4.38.0)
[2023-07-16T16:14:58.619+0000] {subprocess.py:93} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.7/site-packages (from matplotlib) (1.4.4)
[2023-07-16T16:14:58.619+0000] {subprocess.py:93} INFO - Requirement already satisfied: numpy>=1.17 in /home/***/.local/lib/python3.7/site-packages (from matplotlib) (1.21.6)
[2023-07-16T16:14:58.620+0000] {subprocess.py:93} INFO - Requirement already satisfied: packaging>=20.0 in /home/***/.local/lib/python3.7/site-packages (from matplotlib) (21.3)
[2023-07-16T16:14:58.621+0000] {subprocess.py:93} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.7/site-packages (from matplotlib) (9.5.0)
[2023-07-16T16:14:58.621+0000] {subprocess.py:93} INFO - Requirement already satisfied: pyparsing>=2.2.1 in /home/***/.local/lib/python3.7/site-packages (from matplotlib) (3.1.0)
[2023-07-16T16:14:58.622+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil>=2.7 in /home/***/.local/lib/python3.7/site-packages (from matplotlib) (2.8.2)
[2023-07-16T16:14:58.644+0000] {subprocess.py:93} INFO - Requirement already satisfied: pandas>=0.25 in /home/***/.local/lib/python3.7/site-packages (from seaborn) (1.3.5)
[2023-07-16T16:14:58.645+0000] {subprocess.py:93} INFO - Requirement already satisfied: typing_extensions in /home/***/.local/lib/python3.7/site-packages (from seaborn) (4.7.1)
[2023-07-16T16:14:58.704+0000] {subprocess.py:93} INFO - Requirement already satisfied: pytz>=2017.3 in /home/***/.local/lib/python3.7/site-packages (from pandas>=0.25->seaborn) (2023.3)
[2023-07-16T16:14:58.725+0000] {subprocess.py:93} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.7/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
[2023-07-16T16:15:03.382+0000] {subprocess.py:93} INFO - Installing collected packages: seaborn
[2023-07-16T16:15:03.571+0000] {subprocess.py:93} INFO - Successfully installed seaborn-0.12.2
[2023-07-16T16:15:03.580+0000] {subprocess.py:93} INFO - 
[2023-07-16T16:15:03.580+0000] {subprocess.py:93} INFO - [notice] A new release of pip is available: 23.1.2 -> 23.2
[2023-07-16T16:15:03.580+0000] {subprocess.py:93} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2023-07-16T16:15:03.739+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-16T16:15:03.768+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=install_libraries, execution_date=20230716T161444, start_date=20230716T161445, end_date=20230716T161503
[2023-07-16T16:15:03.803+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-16T16:15:03.834+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
