[2023-07-17T08:52:55.045+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.make_figures.plot_all_together manual__2023-07-17T08:41:27.786321+00:00 [queued]>
[2023-07-17T08:52:55.060+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.make_figures.plot_all_together manual__2023-07-17T08:41:27.786321+00:00 [queued]>
[2023-07-17T08:52:55.060+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-17T08:52:55.080+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): make_figures.plot_all_together> on 2023-07-17 08:41:27.786321+00:00
[2023-07-17T08:52:55.090+0000] {standard_task_runner.py:57} INFO - Started process 4481 to run task
[2023-07-17T08:52:55.093+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'make_figures.plot_all_together', 'manual__2023-07-17T08:41:27.786321+00:00', '--job-id', '640', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpjlgb19dt']
[2023-07-17T08:52:55.102+0000] {standard_task_runner.py:85} INFO - Job 640: Subtask make_figures.plot_all_together
[2023-07-17T08:52:55.169+0000] {task_command.py:410} INFO - Running <TaskInstance: main_dag.make_figures.plot_all_together manual__2023-07-17T08:41:27.786321+00:00 [running]> on host 0314a966ffa9
[2023-07-17T08:52:55.324+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='make_figures.plot_all_together' AIRFLOW_CTX_EXECUTION_DATE='2023-07-17T08:41:27.786321+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-17T08:41:27.786321+00:00'
[2023-07-17T08:52:56.466+0000] {font_manager.py:1443} INFO - generated new fontManager
[2023-07-17T09:10:39.038+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2023-07-17T09:10:39.120+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 4481. PIDs of all processes in the group: [4481]
[2023-07-17T09:10:39.125+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 4481
[2023-07-17T09:10:39.293+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-07-17T09:10:39.306+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main_dag.py", line 124, in all_together_figure
    import network as nx
  File "<class 'networkx.utils.decorators.argmap'> compilation 18", line 5, in argmap_betweenness_centrality_14
    import warnings
  File "/home/airflow/.local/lib/python3.7/site-packages/networkx/algorithms/centrality/betweenness.py", line 129, in betweenness_centrality
    S, P, sigma, _ = _single_source_shortest_path_basic(G, s)
  File "/home/airflow/.local/lib/python3.7/site-packages/networkx/algorithms/centrality/betweenness.py", line 257, in _single_source_shortest_path_basic
    P[v] = []
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-07-17T09:10:39.313+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=main_dag, task_id=make_figures.plot_all_together, execution_date=20230717T084127, start_date=20230717T085255, end_date=20230717T091039
[2023-07-17T09:10:39.330+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 640 for task make_figures.plot_all_together (Task received SIGTERM signal; 4481)
[2023-07-17T09:10:39.380+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=4481, status='terminated', exitcode=1, started='08:52:54') (4481) terminated with exit code 1
[2023-07-17T09:10:39.383+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 143
[2023-07-17T09:10:39.434+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-17T09:10:40.953+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2023-07-17T09:10:40.953+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 143
