[2023-07-16T01:32:10.144+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.tsk1 manual__2023-07-16T01:32:08.747587+00:00 [queued]>
[2023-07-16T01:32:10.154+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.tsk1 manual__2023-07-16T01:32:08.747587+00:00 [queued]>
[2023-07-16T01:32:10.154+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-16T01:32:10.173+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): tsk1> on 2023-07-16 01:32:08.747587+00:00
[2023-07-16T01:32:10.177+0000] {standard_task_runner.py:57} INFO - Started process 2279 to run task
[2023-07-16T01:32:10.180+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'tsk1', 'manual__2023-07-16T01:32:08.747587+00:00', '--job-id', '417', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpst10h5bz']
[2023-07-16T01:32:10.181+0000] {standard_task_runner.py:85} INFO - Job 417: Subtask tsk1
[2023-07-16T01:32:10.222+0000] {task_command.py:410} INFO - Running <TaskInstance: main_dag.tsk1 manual__2023-07-16T01:32:08.747587+00:00 [running]> on host 3be1cdcf9db5
[2023-07-16T01:32:10.334+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='tsk1' AIRFLOW_CTX_EXECUTION_DATE='2023-07-16T01:32:08.747587+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-16T01:32:08.747587+00:00'
[2023-07-16T01:32:10.335+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-16T01:32:10.336+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec ***-project_***-scheduler_1 bash pip install networkx']
[2023-07-16T01:32:10.345+0000] {subprocess.py:86} INFO - Output:
[2023-07-16T01:32:10.363+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2023-07-16T01:32:10.366+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-07-16T01:32:10.377+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-07-16T01:32:10.380+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=main_dag, task_id=tsk1, execution_date=20230716T013208, start_date=20230716T013210, end_date=20230716T013210
[2023-07-16T01:32:10.392+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 417 for task tsk1 (Bash command failed. The command returned a non-zero exit code 1.; 2279)
[2023-07-16T01:32:10.432+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-16T01:32:10.449+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
