[2023-07-16T04:10:20.019+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.read_data manual__2023-07-16T04:10:11.493603+00:00 [queued]>
[2023-07-16T04:10:20.029+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.read_data manual__2023-07-16T04:10:11.493603+00:00 [queued]>
[2023-07-16T04:10:20.030+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-16T04:10:20.044+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): read_data> on 2023-07-16 04:10:11.493603+00:00
[2023-07-16T04:10:20.048+0000] {standard_task_runner.py:57} INFO - Started process 570 to run task
[2023-07-16T04:10:20.051+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'read_data', 'manual__2023-07-16T04:10:11.493603+00:00', '--job-id', '469', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpx6kzcok1']
[2023-07-16T04:10:20.054+0000] {standard_task_runner.py:85} INFO - Job 469: Subtask read_data
[2023-07-16T04:10:20.095+0000] {task_command.py:410} INFO - Running <TaskInstance: main_dag.read_data manual__2023-07-16T04:10:11.493603+00:00 [running]> on host 85db40224008
[2023-07-16T04:10:20.184+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='read_data' AIRFLOW_CTX_EXECUTION_DATE='2023-07-16T04:10:11.493603+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-16T04:10:11.493603+00:00'
[2023-07-16T04:10:20.475+0000] {python.py:183} INFO - Done. Returned value was: Graph with 4039 nodes and 88234 edges
[2023-07-16T04:10:20.484+0000] {xcom.py:640} ERROR - Object of type Graph is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-07-16T04:10:20.485+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/serialization/serde.py", line 172, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'networkx.classes.graph.Graph'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2361, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 243, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 632, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Graph is not JSON serializable
[2023-07-16T04:10:20.495+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=main_dag, task_id=read_data, execution_date=20230716T041011, start_date=20230716T041020, end_date=20230716T041020
[2023-07-16T04:10:20.510+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 469 for task read_data (Object of type Graph is not JSON serializable; 570)
[2023-07-16T04:10:20.545+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-16T04:10:20.574+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
